### ISSUE TITLE
Python issue in Kodi v19 beta

### ISSUE THREAD

**Issue by tekwarp** [axlt2002/repo.light.imdb.ratings.update#1]
Hi,

I managed to get both version installed in v19 by modifying addon.xml to:
<import addon="xbmc.python" version="3.0.0" />  but I still run into this error for both 3.5.4 and 4.2.2 versions.

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'TabError'>
                 Error Contents: inconsistent use of tabs and spaces in indentation (service.py, line 28)
                   File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\script.light.imdb.ratings.update\service.py", line 28
                     day_difference = -day_difference
                 TabError: inconsistent use of tabs and spaces in indentation
                 -->End of Python script error report<--

Any ideas?

**Comment by axlt2002** [comment]
Hi @tekwarp,

Sorry for replying back to this issue so late. Version 4.3.0 is now available and compatible with Kodi 19.

Best Regards,

Alex
