### ISSUE TITLE
Addon not working on new Libreelec 11

### ISSUE THREAD

**Issue by UserX404** [axlt2002/repo.light.imdb.ratings.update#4]
I updated Libreelec on my Rasp4 and light imdb addon doesn't work anymore.

Libreelec: 11.0.0
Plugin Version: 5.0.1
Logs: http://ix.io/4qV4

**Comment by SelmaUrban** [comment]
Update to Version 5.1.1

**Comment by UserX404** [comment]
Oh, thank you.
Didn't notice i ran a outdated version.
It works again after the update.
